name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.kube.lampamc.ru/nico/kratos-web:latest
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REPO }}
        username: ${{ secrets.REPO_LOGIN }}
        password: ${{ secrets.RPEO_PASS }}
    - name: Push the Docker image
      run: docker push registry.kube.lampamc.ru/nico/kratos-web:latest
